apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-basic-java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-basic-java
  template:
    metadata:
      labels:
        app: app-basic-java
    spec:
      containers:
        - name: app-basic-java
          image: swr.la-south-2.myhuaweicloud.com/cce-basic-app/app-basic-java:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: TZ
              value: "UTC-5"
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
