apiVersion: v1
kind: Service
metadata:
  name: mi-app-service
spec:
  type: LoadBalancer
  selector:
    app: mi-app
  ports:
    - port: 80        # Puerto p√∫blico
      targetPort: 8080 # Puerto interno del container
